### ISSUE TITLE
Issues with the TPP HTML examples in the Demonstrator

### ISSUE THREAD

**Issue by michaelmeasures** [nhs-digital/gpconnect#10]
The Patient Summary section for TPP patient has the following problems:

- Patient Summary Section has Key Indicators, Warnings, Investigations and Recalls which are out of scope for Stage 1
- Patient Summary Section Active Probs has table layout for Current Repeat Medications and vice versa
- Patient Summary Section Current Med Issues missing columns
- Investigations still on left hand menu

**Comment by james-answer** [comment]
All pages are now dynamically built so the issue no longer exists.
