### ISSUE TITLE
If authorization header is not include the request still succeeds

### ISSUE THREAD

**Issue by james-answer** [nhs-digital/gpconnect#13]
If authorization header is not include the request still succeeds when it should return a 400 for a bad request.

**Comment by wilkinsm** [comment]
From what I've witnessed in other similar tests the Authorization header is removed as a Step in Tests and then re-added in a later Test Step which is why the request Succeeds.

**Book appointment failure due to missing header** test now works as expected as it handles the header removal correctly.

**Comment by james-answer** [comment]
This has now been resolved.
