### ISSUE TITLE
OperationOutcome resource within a resource bundle is missing most of the mandatory fields

### ISSUE THREAD

**Issue by Chrisjobling** [nhs-digital/gpconnect#5]
The OperationOutcome resource within a resource bundle is missing most of the mandatory fields
 
Response.xml FAIL "OperationOutcome Profile NOT as expected"
Failed -- Xpath $OperationOutcome/meta/profile/@value returned "" when "http://.nhs.net/StructureDefinition/gpconnect-operationoutcome-1" was expected
 
Response.xml FAIL "OperationOutcome Issue Code NOT as expected"
Failed -- Xpath $OperationOutcome/issue/code/@value returned no match
 
Response.xml FAIL "OperationOutcome Issue Details NOT as expected"
Failed -- Xpath $OperationOutcome/issue/details returned no match
 
Response.xml FAIL "OperationOutcome Issue Details Coding NOT as expected"
Failed -- Xpath $OperationOutcome/issue/details/coding returned no match
 
Response.xml FAIL "OperationOutcome Issue Details Coding System NOT as expected"
Failed -- Xpath $OperationOutcome/issue/details/coding/system/@value returned "" when "http://.nhs.net/ValueSet/gpconnect-error-or-warning-code-1" was expected
 
Response.xml FAIL "OperationOutcome Issue Details Coding Code NOT as expected"
Failed -- Xpath //issue/details/coding/code/@value returned no match
 
Response.xml FAIL "OperationOutcome Issue Details Coding Display NOT as expected"
Failed -- Xpath //issue/details/coding/display/@value returned no match
 
 
 
Response xml contains Patient/Practititioner/Organization/Composition and the OperationOutcome
 
            <entry>
                        <resource>
                                    <OperationOutcome>
                                                <issue>
                                                            <severity value="error"/>
                                                            <diagnostics value="No data available for the requested section: AdministrativeItems"/>
                                                </issue>
                                    </OperationOutcome>
                        </resource>
            </entry>

**Comment by james-answer** [comment]
The demonstrator should be returning HTML with the no data available HTML banner text from the specification in each section rather than returning an OperationOutcome within the bundle. So we should change the demonstrator to produce the HTML and remove the OperationOutcome.

**Comment by james-answer** [comment]
The demonstrator has been updated to return an the HTML and a banner rather than an OperationOutcome in the bundle so this should no longer be a problem.
